CREATE TABLE product(`id` INTEGER PRIMARY KEY, `name` TEXT NOT NULL, `description` TEXT NOT NULL, `price` INTEGER NOT NULL, `image` BINARY);
CREATE TABLE cart(`id` INTEGER NOT NULL, `product_id` INTEGER NOT NULL, `quantity` INTEGER NOT NULL);
CREATE TABLE user(`id` INTEGER PRIMARY KEY, `name` TEXT NOT NULL, `email` TEXT UNIQUE NOT NULL, `password` TEXT NOT NULL, `cart_id` INTEGER);
